spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_assingment
    username: awais
    password: ak1020
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

